# Generated by Django 4.2 on 2024-06-10 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo1', models.CharField(max_length=50)),
                ('titulo2', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('presio', models.IntegerField()),
                ('habitaciones', models.IntegerField()),
                ('banios', models.IntegerField()),
                ('huespedes', models.IntegerField()),
                ('area', models.IntegerField()),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamentos.barrio')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenDepartamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='producto')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.departamento')),
            ],
        ),
    ]
