# Generated by Django 4.2 on 2024-06-10 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='presio',
            new_name='precio',
        ),
    ]
