# Generated by Django 4.2 on 2024-06-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_rename_presio_departamento_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='clave',
            field=models.IntegerField(null=True),
        ),
    ]
