# Generated by Django 4.2 on 2024-06-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_departamento_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='descripcion1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='descripcion2',
            field=models.TextField(null=True),
        ),
    ]
