# Generated by Django 4.2 on 2024-06-17 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0004_departamento_descripcion1_departamento_descripcion2'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='moneda',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='clave',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='imagendepartamentos',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='departamentos.departamento'),
        ),
    ]
