# Generated by Django 4.2 on 2024-06-17 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0005_departamento_moneda_alter_departamento_clave_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='moneda',
        ),
    ]
