# Generated by Django 4.2 on 2024-06-17 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0006_remove_departamento_moneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='moneda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='departamentos.moneda'),
        ),
    ]
