# Generated by Django 4.2 on 2024-06-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0007_moneda_departamento_moneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('lat', models.FloatField(verbose_name='Latitud')),
                ('lng', models.FloatField(verbose_name='Longitud')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
