# Generated by Django 4.2 on 2024-06-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0008_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name_plural': 'Ubicacion'},
        ),
        migrations.AlterField(
            model_name='location',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Depto'),
        ),
    ]
