# Generated by Django 4.2 on 2024-06-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0010_alter_location_direccion_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
